language: node_js

sudo: false

node_js:
  - node  # test on latest version
  - 6
  - 5
  - 4

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm run semantic-release

matrix:
  fast_finish: true

notifications:
  email: false

branches:
  except:
    # Ignore tags created by semantic-release
    - /^v\d+\.\d+\.\d+$/
