language: node_js
sudo: false

node_js:
    - node
    - iojs
    - 6
    - 5
    - 4

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - npm install -g karma-cli grunt-cli bower

before_script:
    - npm install && bower install

script:
    - grunt karma

matrix:
  fast_finish: true
